version: '2'

volumes:
  nextcloud:
  db:

services:
  app:
    image: nextcloud
    restart: always
    ports:
      - 8087:80
    links:
      - db
    volumes:
      - /opt/docker/nextcloud/html:/var/www/html
    environment:
      - MYSQL_PASSWORD=$NCDBUSER
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - internal
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.entrypoints: web,websecure
      traefik.http.routers.nextcloud.rule: Host(`nextcloud.$DOMAINNAME`)
      traefik.http.routers.nextcloud.tls: true
      traefik.http.routers.nextcloud.tls.certresolver: production
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /opt/docker/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$NCDBROOT
      - MYSQL_PASSWORD=$NCDBUSER
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - internal

networks:
  internal:
    external: true