version: '3.3'
services:
    radarr:
        container_name: radarr
        ports:
            - 7878:7878
        environment:
            - PUID=1000
            - PGID=1000
            - HOME=/root
            - TERM=xterm
            - XDG_CONFIG_HOME=/config/xdg
            - LANGUAGE=en_US.UTF-8
            - LANG=en_US.UTF-8
        volumes:
          - /etc/localtime:/etc/localtime
          - $DOCKERPATH/radarr:/config
          - $MEDIAPATH:/mnt/Media
        networks:
          - internal
        labels:
          traefik.enable: true
          traefik.http.routers.radarr.entrypoints: web,websecure
          traefik.http.routers.radarr.rule: Host(`radarr.$DOMAINNAME`)
          traefik.http.routers.radarr.tls: true
          traefik.http.routers.radarr.tls.certresolver: production
          traefik.http.routers.radarr.middlewares: traefik-forward-auth
        restart: always
        image: 'linuxserver/radarr:latest'
networks:
  internal:
    external: true