version: '3.3'
services:
    netdata:
        container_name: netdata
        ports:
            - 19999:19999
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - internal
        labels:
          traefik.enable: true
          traefik.http.routers.netdata.entrypoints: web,websecure
          traefik.http.routers.netdata.rule: Host(`netdata.$DOMAINNAME`)
          traefik.http.routers.netdata.tls: true
          traefik.http.routers.netdata.tls.certresolver: production
          traefik.http.routers.netdata.middlewares: traefik-forward-auth
        restart: always
        image: titpetric/netdata
networks:
  internal:
    external: true