version: '3.3'
services:
    pms-docker:
        container_name: plex
#        devices:
#            - /dev/dri:/dev/dri
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        environment:
            - TZ=America/Denver
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
            - PLEX_CLAIM=$PLEXCLAIM
        networks:
          - internal
          - external
        volumes:
          - $DOCKERPATH/plex/database:/config
          - /dev/shm:/transcode
          - $MEDIAPATH:/mnt/unionfs/Media
        labels:
          traefik.enable: true
          traefik.http.routers.plex.entrypoints: web,websecure
          traefik.http.routers.plex.rule: Host(`plex.$DOMAINNAME`)
          traefik.http.routers.plex.tls: true
          traefik.http.routers.plex.tls.certresolver: production
          traefik.http.routers.plex.middlewares: traefik-forward-auth
          traefik.http.services.plex.loadbalancer.server.port: 32400
        restart: always
        image: plexinc/pms-docker
networks:
  internal:
    external: true
  external:
    external: true
