version: '3.3'
services:
    sonarr:
        container_name: sonarr
        ports:
            - 8989:8989
        environment:
            - PUID=1000
            - PGID=1000
            - HOME=/root
            - TERM=xterm
            - XDG_CONFIG_HOME=/config/xdg
            - LANGUAGE=en_US.UTF-8
            - LANG=en_US.UTF-8
        volumes:
          - /etc/localtime:/etc/localtime
          - $DOCKERPATH/sonarr:/config
          - $MEDIAPATH:/mnt/Media
        networks:
          - internal
        labels:
          traefik.enable: true
          traefik.http.routers.sonarr.entrypoints: web,websecure
          traefik.http.routers.sonarr.rule: Host(`sonarr.$DOMAINNAME`)
          traefik.http.routers.sonarr.tls: true
          traefik.http.routers.sonarr.tls.certresolver: production
          traefik.http.routers.sonarr.middlewares: traefik-forward-auth
        restart: always
        image: linuxserver/sonarr:latest
networks:
  internal:
    external: true