version: '3.3'
services:
    speedtest:
        container_name: speedtest
        ports:
            - 8223:8223
        environment:
            - PUID=1000
            - PGID=1000
            - TITLE=$DOMAINNAME
            - WEBPORT=8223
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - internal
        labels:
          traefik.enable: true
          traefik.http.routers.speedtest.entrypoints: web,websecure
          traefik.http.routers.speedtest.rule: Host(`speedtest.$DOMAINNAME`)
          traefik.http.routers.speedtest.tls: true
          traefik.http.routers.speedtest.tls.certresolver: production
          traefik.http.routers.speedtest.middlewares: traefik-forward-auth
        restart: always
        image: adolfintel/speedtest
networks:
  internal:
    external: true