# Google OAuth - Single Sign On using OAuth 2.0 for Traefik 2.2
version: '3.3'

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - internal
      - external
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "9980:8080"  # Don't do this in production!
    volumes:
      - /mnt/docker/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
  traefik-forward-auth:
    container_name: traefik-forward-auth
    image: thomseddon/traefik-forward-auth:latest
    # image: thomseddon/traefik-forward-auth:2.1-arm # Use this image with Raspberry Pi
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "4181:4181"
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=$OAUTHCLIENT
      - PROVIDERS_GOOGLE_CLIENT_SECRET=$OAUTHSECRET
      - SECRET=$SECRETKEY
      - COOKIE_DOMAIN=$DOMAINNAME
      - URL_PATH=/_oauth
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.$DOMAINNAME
      - WHITELIST=$AUTHORIZEDUSERS
      - LOG_LEVEL=debug
    labels:
      traefik.enable: true
      traefik.http.middlewares.traefik-forward-auth.forwardauth.address: http://traefik-forward-auth:4181
      traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders: X-Forwarded-User
      traefik.http.routers.traefik-forward-auth.rule: Host(`oauth.interwebnet.net`)
      traefik.http.routers.traefik-forward-auth.tls: true
      traefik.http.services.traefik-forward-auth.loadbalancer.server.port: 4181
      traefik.http.routers.traefik-forward-auth.tls.certresolver: production


networks:
  internal:
    external: true
  external:
    external: true
